### ISSUE TITLE
AIML assignments 

### ISSUE THREAD

**Issue by Parrurox** [saha-indranil/sem4#1]
PS aiml assignments are not matching , also update it pls. thank you

**Comment by Shback007** [comment]
It's because AIML assignment of our stream is different

**Comment by saha-indranil** [comment]
if assignments are not matching, you are welcomed to contribute for your section :)

**Comment by Parrurox** [comment]
> if assignments are not matching, you are welcomed to contribute for your section :)

okay and thanks
